/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch POI display data (not yet implemented) */
        get: operations["get_place_detail_api_places__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description What each engine supports, and the drag-throttle budget per leg intent.
         *
         *     The frontend reads `live_update_interval_ms` from here rather than hardcoding a
         *     per-engine constant, so retuning throttles is a backend config change.
         */
        get: operations["capabilities_api_routing_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing/leg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Leg
         * @description Route a single leg.
         *
         *     Called on every throttled drag update and again on release, so it must stay cheap.
         *     Routing errors are translated to HTTP by the registered exception handlers.
         */
        post: operations["route_leg_api_routing_leg_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_trips_get"];
        put?: never;
        /**
         * Create Trip
         * @description Create an empty trip.
         *
         *     An explicit slug is validated strictly; a derived one is slugified from the name.
         *     Either way it is checked before it can become a storage path.
         */
        post: operations["create_trip_api_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_trips__slug__get"];
        /**
         * Update Trip
         * @description Apply a partial update, refusing to clobber a concurrent edit.
         *
         *     Trips are public and world-editable, so two riders editing the same trip from a shared
         *     link is ordinary. An unconditional write would not merely lose the slower writer's edit —
         *     it would roll back fields that writer never touched, and answer 200 as though the data
         *     had been saved. So the write carries the version it was read at, and a conflict re-reads
         *     and re-merges rather than surfacing immediately.
         *
         *     Raises:
         *         TripModifiedConcurrently: still contended after `MAX_UPDATE_ATTEMPTS`; maps to 409.
         *         TripNotFound: no such trip, including one deleted mid-update — writing anyway would
         *             resurrect something somebody chose to remove.
         */
        put: operations["update_trip_api_trips__slug__put"];
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_trips__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{slug}/gpx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export GPX (not yet implemented)
         * @description Returns a GPX file containing a track plus ordered waypoints, targeted at motorcycle GPS units.
         */
        get: operations["export_gpx_api_trips__slug__gpx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{slug}/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover points of interest along the route
         * @description Runs web search, place extraction, Places resolution and scoring over the trip's corridor. Streams application/x-ndjson: one ReplanEvent per line, POIs accumulating as they resolve so the map fills in rather than waiting. Not Server-Sent Events — there is no `data:` prefix and no blank-line framing. Explicitly user-triggered; never fired automatically by a route edit. Answers 501 when the discovery credentials are not configured.
         */
        post: operations["replan_api_trips__slug__replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Coordinate
         * @description A WGS84 point.
         *
         *     Frozen and hashable so requests built from coordinates can be used as cache keys.
         */
        Coordinate: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * CreateTripRequest
         * @description Create a trip. Everything is public and unauthenticated for now.
         */
        CreateTripRequest: {
            /** Name */
            name: string;
            /**
             * Slug
             * @description Explicit slug. Omit to derive one from the name.
             */
            slug?: string | null;
        };
        /**
         * ErrorCode
         * @description Stable, machine-readable error identifiers.
         *
         *     Clients switch on these. `detail` is for humans and is not part of the contract.
         *     Renaming a member is a breaking change; adding one is not.
         * @enum {string}
         */
        ErrorCode: "invalid_request" | "unsupported_intent" | "provider_not_found" | "no_route_found" | "route_incomplete" | "quota_exceeded" | "rate_limited" | "provider_unavailable" | "llm_unavailable" | "llm_quota_exceeded" | "llm_refused" | "tool_call_failed" | "invalid_slug" | "trip_not_found" | "trip_already_exists" | "trip_modified_concurrently" | "trip_document_invalid" | "trip_storage_unavailable" | "validation_error" | "not_implemented" | "internal_error";
        /**
         * ErrorResponse
         * @description Uniform error body. `code` is stable and machine-readable; `detail` is for humans.
         */
        ErrorResponse: {
            /** @description Stable, machine-readable error identifier. Switch on this, never on `detail`. Typed as an enum so the frontend generates the union instead of hand-maintaining it. */
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Providers */
            providers: string[];
            /** Status */
            status: string;
        };
        /**
         * IntentRouting
         * @description How one leg intent is currently routed, and how fast the UI may re-request it.
         */
        IntentRouting: {
            /**
             * Live Update Interval Ms
             * @description Minimum milliseconds between live re-routes while dragging. null means preview-only: rubber-band locally and route only on release.
             */
            live_update_interval_ms?: number | null;
            /** Provider */
            provider: string;
        };
        /**
         * LegIntent
         * @description What a leg is *for*. The policy resolver maps this to a provider and profile.
         *
         *     This is the unit of "different routing algorithm per road type" — it is a property
         *     of trip data, not a branch in routing code.
         * @enum {string}
         */
        LegIntent: "highway_connector" | "twisty_paved" | "unpaved" | "technical_offroad" | "manual_track";
        /**
         * Poi
         * @description A point of interest, as persisted in the trip document.
         */
        Poi: {
            category: components["schemas"]["PoiCategory"];
            coordinate: components["schemas"]["Coordinate"];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
            /**
             * On Route
             * @default false
             */
            on_route: boolean;
            /** Place Id */
            place_id?: string | null;
            source: components["schemas"]["PoiSource"];
        };
        /**
         * PoiCategory
         * @description What a point of interest is, which drives its map icon and discovery prompt.
         * @enum {string}
         */
        PoiCategory: "wild_camp" | "campground" | "hotel" | "unique_stay" | "food" | "fuel" | "water" | "viewpoint" | "mechanic";
        /**
         * PoiDetail
         * @description Display data for the POI dialog. Response-only — never written to storage.
         *
         *     Everything beyond `poi` is re-fetched from Places on demand, because caching it would
         *     breach Google's terms.
         */
        PoiDetail: {
            /**
             * Opening Hours
             * @default []
             */
            opening_hours: string[];
            /** Phone */
            phone?: string | null;
            /**
             * Photo Urls
             * @default []
             */
            photo_urls: string[];
            poi: components["schemas"]["Poi"];
            /** Rating */
            rating?: number | null;
            /**
             * Reviews
             * @default []
             */
            reviews: string[];
            /** User Rating Count */
            user_rating_count?: number | null;
            /** Website */
            website?: string | null;
        };
        /**
         * PoiDetailResponse
         * @description Places-backed display data for the POI dialog.
         *
         *     Never cached server-side beyond `place_id`; Google's terms do not permit it.
         */
        PoiDetailResponse: {
            detail: components["schemas"]["PoiDetail"];
        };
        /**
         * PoiSource
         * @description Where a POI came from, which determines how far to trust its coordinates.
         * @enum {string}
         */
        PoiSource: "llm_suggested" | "places" | "user";
        /**
         * ProviderCapabilities
         * @description What a provider can do and what it costs.
         *
         *     The policy resolver dispatches on these fields rather than on provider names, so
         *     adding an engine never touches dispatch logic.
         */
        ProviderCapabilities: {
            /**
             * Alternatives
             * @default false
             */
            alternatives: boolean;
            /** Daily Quota */
            daily_quota?: number | null;
            /**
             * Elevation
             * @default false
             */
            elevation: boolean;
            /** Live Update Interval Ms */
            live_update_interval_ms?: number | null;
            /**
             * Map Matching
             * @default false
             */
            map_matching: boolean;
            /**
             * Max Waypoints
             * @default 50
             */
            max_waypoints: number;
            /** Name */
            name: string;
            /** Per Minute Quota */
            per_minute_quota?: number | null;
            /**
             * Prefers Unpaved
             * @default false
             */
            prefers_unpaved: boolean;
            /**
             * Reports Surface
             * @default false
             */
            reports_surface: boolean;
        };
        /**
         * ReplanEvent
         * @description One streamed progress event from a replan.
         */
        ReplanEvent: {
            /**
             * Legs
             * @description Legs re-routed by this stage, if any.
             */
            legs?: components["schemas"]["TripLeg"][];
            /** Message */
            message: string;
            /**
             * Pois
             * @description POIs discovered so far in this stage. Cumulative per stage, not total.
             */
            pois?: components["schemas"]["Poi"][];
            /** Progress */
            progress?: number | null;
            /**
             * Stage
             * @description One of: route_search, discovery, enrichment, done.
             */
            stage: string;
        };
        /**
         * ReplanRequest
         * @description Start the slow path. Explicitly user-triggered; never fired by a route edit.
         */
        ReplanRequest: {
            /**
             * Categories
             * @description Which kinds of POI to discover along the route.
             */
            categories?: components["schemas"]["PoiCategory"][];
            /**
             * Preserve Pinned
             * @description Keep POIs the user pinned and legs they have not touched, rather than discarding the whole plan.
             * @default true
             */
            preserve_pinned: boolean;
            /**
             * Prompt
             * @description Free-text steer from the chat bar, e.g. 'prefer hot springs'.
             */
            prompt?: string | null;
        };
        /**
         * RouteFingerprint
         * @description The request a leg's geometry was produced from.
         *
         *     Recorded so staleness is decidable rather than guessed. Comparing a cached leg's
         *     endpoints against its waypoints cannot work — engines snap to the nearest routable node,
         *     sometimes by hundreds of metres, so there is no tolerance that separates snapping from a
         *     user dragging the point. Comparing the *request* has no such ambiguity.
         *
         *     Stores rounded coordinates rather than a hash. A hash would be smaller and sufficient for
         *     equality, but when a rider reports a route wrongly marked stale, a hash says nothing and
         *     these values name the field that moved.
         */
        RouteFingerprint: {
            intent: components["schemas"]["LegIntent"];
            /** Provider Override */
            provider_override?: string | null;
            /** Waypoints */
            waypoints: components["schemas"]["Coordinate"][];
        };
        /**
         * RouteLeg
         * @description A routed leg, normalized across providers.
         */
        RouteLeg: {
            /** Ascent M */
            ascent_m?: number | null;
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Geometry */
            geometry: components["schemas"]["Coordinate"][];
            intent: components["schemas"]["LegIntent"];
            /** Provider */
            provider: string;
            routed_from?: components["schemas"]["RouteFingerprint"] | null;
            /**
             * Surface Spans
             * @default []
             */
            surface_spans: components["schemas"]["SurfaceSpan"][];
        };
        /**
         * RouteLegRequest
         * @description Route one leg. The fast path — no LLM involvement, no persistence.
         */
        RouteLegRequest: {
            /**
             * Avoid Ferries
             * @default false
             */
            avoid_ferries: boolean;
            /**
             * Avoid Highways
             * @default false
             */
            avoid_highways: boolean;
            /**
             * Avoid Tolls
             * @default false
             */
            avoid_tolls: boolean;
            intent: components["schemas"]["LegIntent"];
            /**
             * Provider Override
             * @description Pin this leg to a named engine, bypassing the policy table.
             */
            provider_override?: string | null;
            /**
             * Want Elevation
             * @default false
             */
            want_elevation: boolean;
            /** Waypoints */
            waypoints: components["schemas"]["Coordinate"][];
        };
        /** RouteLegResponse */
        RouteLegResponse: {
            leg: components["schemas"]["RouteLeg"];
            /**
             * Live Update Interval Ms
             * @description Throttle budget for the engine that served this leg.
             */
            live_update_interval_ms?: number | null;
        };
        /**
         * RoutingCapabilitiesResponse
         * @description Lets the frontend throttle per provider without hardcoding an engine name.
         */
        RoutingCapabilitiesResponse: {
            /** Intents */
            intents: {
                [key: string]: components["schemas"]["IntentRouting"];
            };
            /** Providers */
            providers: components["schemas"]["ProviderCapabilities"][];
        };
        /**
         * Surface
         * @enum {string}
         */
        Surface: "paved" | "unpaved" | "unknown";
        /**
         * SurfaceSpan
         * @description A run of geometry sharing one surface type, as inclusive indices into `geometry`.
         */
        SurfaceSpan: {
            /** End Index */
            end_index: number;
            /** Start Index */
            start_index: number;
            surface: components["schemas"]["Surface"];
        };
        /**
         * Trip
         * @description A saved trip. Serialized verbatim to `trips/<slug>/trip.json`.
         */
        Trip: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
            /**
             * Estimated Duration S
             * @description Riding time derived from distance and surface.
             *
             *     Not the provider's figure. Hosted ORS routes dirt through a bicycle profile and
             *     reports bicycle times, so `RouteLeg.duration_s` is honest about what the engine said
             *     and useless for telling a rider how long their day is.
             */
            readonly estimated_duration_s: number;
            /**
             * Legs
             * @default []
             */
            legs: components["schemas"]["TripLeg"][];
            /** Name */
            name: string;
            /** Planned At */
            planned_at?: string | null;
            /**
             * Pois
             * @default []
             */
            pois: components["schemas"]["Poi"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Slug */
            slug: string;
            /** Total Distance M */
            readonly total_distance_m: number;
            /**
             * Total Paved Fraction
             * @description Share of the trip on surfaced road, weighted by distance.
             */
            readonly total_paved_fraction: number;
            /**
             * Total Unknown Fraction
             * @description Share of the trip whose surface nobody has recorded.
             *
             *     Reported as its own number so the UI can show three states. Folded into either of
             *     the others it disappears, and it disappears into whichever the client treats as the
             *     default — which is how an unsurveyed forest road comes to be displayed as tarmac.
             */
            readonly total_unknown_fraction: number;
            /**
             * Total Unpaved Fraction
             * @description Share of the whole trip on dirt, weighted by leg distance.
             *
             *     Both sides of the ratio are measured from geometry. Dividing geometry-derived
             *     unpaved metres by the provider's reported `distance_m` mixes two denominators that
             *     need not agree, and the error compounds across legs. `total_distance_m` still
             *     reports the provider's figure, which is the better number to *display*.
             *
             *     Weighting by distance also matters: averaging per-leg fractions would let a short
             *     dirt connector beside a long highway read as half the trip.
             */
            readonly total_unpaved_fraction: number;
            /**
             * Waypoints
             * @default []
             */
            waypoints: components["schemas"]["Waypoint"][];
        };
        /**
         * TripLeg
         * @description One section of the route, spanning a pair of waypoints.
         *
         *     Each leg carries its own intent and optional provider override, which is what makes
         *     per-road-type routing a property of the data rather than a branch in routing code.
         */
        TripLeg: {
            /** End Waypoint Index */
            end_waypoint_index: number;
            intent: components["schemas"]["LegIntent"];
            last_routing_error?: components["schemas"]["ErrorCode"] | null;
            /** Provider Override */
            provider_override?: string | null;
            routed?: components["schemas"]["RouteLeg"] | null;
            /** Start Waypoint Index */
            start_waypoint_index: number;
        };
        /**
         * TripSummary
         * @description Listing entry. Avoids shipping full geometry for every trip in the index.
         */
        TripSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
            /**
             * Estimated Duration S
             * @default 0
             */
            estimated_duration_s: number;
            /** Name */
            name: string;
            /** Needs Replan */
            needs_replan: boolean;
            /** Slug */
            slug: string;
            /** Total Distance M */
            total_distance_m: number;
            /**
             * Total Paved Fraction
             * @default 0
             */
            total_paved_fraction: number;
            /**
             * Total Unknown Fraction
             * @default 0
             */
            total_unknown_fraction: number;
            /**
             * Total Unpaved Fraction
             * @default 0
             */
            total_unpaved_fraction: number;
        };
        /**
         * UpdateTripRequest
         * @description Replace a trip's editable content.
         *
         *     A full replacement rather than a patch: the frontend holds the authoritative trip
         *     state while editing, and partial updates would need conflict rules that an
         *     unauthenticated prototype cannot enforce anyway.
         */
        UpdateTripRequest: {
            /** Legs */
            legs?: components["schemas"]["TripLeg"][] | null;
            /** Name */
            name?: string | null;
            /** Pois */
            pois?: components["schemas"]["Poi"][] | null;
            /** Waypoints */
            waypoints?: components["schemas"]["Waypoint"][] | null;
        };
        /**
         * Waypoint
         * @description An anchor the route must pass through.
         */
        Waypoint: {
            coordinate: components["schemas"]["Coordinate"];
            /** Name */
            name?: string | null;
            /**
             * Pinned
             * @default true
             */
            pinned: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_place_detail_api_places__place_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Successful Response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    capabilities_api_routing_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingCapabilitiesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    route_leg_api_routing_leg_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteLegRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteLegResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_trips_api_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummary"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_trip_api_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_trip_api_trips__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_trip_api_trips__slug__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_trip_api_trips__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_gpx_api_trips__slug__gpx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GPX file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/gpx+xml": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Successful Response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replan_api_trips__slug__replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["ReplanEvent"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
